### ISSUE TITLE
Most colors not working in IDEA 2022.1

### ISSUE THREAD

**Issue by lost-name** [Hiberbee/code-highlight-themes#68] opened 2022-04-14 13:12 UTC
**Describe the bug**
Most colors seem to change after closing the settings window. I can't locate the setting that causes this.

Before closing settings:
![image](https://user-images.githubusercontent.com/19654615/163397421-93987659-c516-47dd-be39-fc98b6b834cf.png)

After closing settings:
![image](https://user-images.githubusercontent.com/19654615/163397547-7f46baac-f99f-421d-b124-3fece628e5a0.png)

**To Reproduce**
1. Change theme to Hiberbee Dark in *Preferences -> Appearance and Behavior -> Appearance*
2. Click apply (do not click Ok)
3. The colors in the code behind the settings window look correct right now.
4. Click OK to close the window
5. After a few seconds, most colors change to a dark grey.

**Comment by lost-name** [comment] 2022-04-14 13:19
This may be an issue with Intellij. I'm finding that some hot key combinations cause colors to change until the escape key is pressed.

**Comment by nickroot** [comment] 2022-04-16 18:08
I am seeing the same thing on version 2022.1

**Comment by BLWedge09** [comment] 2022-04-22 13:12
Same thing here.  Wasn't an issue until updating to 2022.1

**Comment by jancoufal** [comment] 2022-04-25 13:50
Seems like a duplicate of https://github.com/hiberbee/jetbrains-ide-theme/issues/49 (where the solution is mentioned).

See https://github.com/hiberbee/jetbrains-ide-theme/issues/49#issuecomment-894914744
> Okay so I found the fix for this in the reviews section of the plugin, you go to Settings > Editor > Color Scheme > Java > Visibility and uncheck the the foreground color under the Visibility section ([review here](https://plugins.jetbrains.com/plugin/12118-hiberbee-theme/reviews#review=57362-57689)). Hopefully that helps!

**Comment by zhaob1n** [comment] 2022-04-26 05:19
same thing here

**Comment by bediazu** [comment] 2022-05-02 15:25
Same thing here, i had to return 2021 version

**Comment by vladyslavvolkov** [comment] 2022-05-16 19:01
@bediazu @hzb-ykpcx @BLWedge09 @nickroot I've published 2022.5.16 release, should be available soon. Please, let me know if issue still persist.

**Comment by nickroot** [comment] 2022-05-23 19:32
@VladyslavVolkov all looks good, Thank you for following with a fix on this.

**Closed as completed** 2022-05-24 12:34 UTC
Labels: bug, released, intellij
